### ISSUE TITLE
How to generate/save the surface mesh

### ISSUE THREAD

**Issue by Paddy-Xu** [LudovicoGranata/VascularNetwork#1]
Hi,

Thanks a lot for the interesting work. I understand that the last step is to plot the surface by plot_surface from matplotlib. I am just wondering is it possible to to create a surface mesh out of it?

Thank you in advance!

**Comment by LudovicoGranata** [comment]
Hi, 
sorry for the late reply. I don't think that it is possible with matplotlib (to my knowledge), but it could be interesting to use some other library to do it starting from the coordinates of the segments.
